// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://goshfdcvsbslvmfvgixb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdvc2hmZGN2c2JzbHZtZnZnaXhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNjM5MDUsImV4cCI6MjA2NjgzOTkwNX0._LySVXW4og6Tjz2E7lUwMel46HbB_mZidXRKK1dYpJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});